### ISSUE TITLE
Git branch workflow test

### ISSUE THREAD

**Issue by ruxandra-valcu** [OceanStreamIO/echopype-scratchpad#2]
Clone the repo to your local system, create a branch and place the existing pyecholab code in there (let's say,in a folder called one-off notebooks) and then merge the branch back to main. You should have full permissions for that, if there are any issues contact me or Andrei

**Comment by simedroniraluca** [comment]
**Possible error: Unable to install 'echolab2' library via pip**

While trying to install the 'echolab2' library using pip, I encountered the following error message:

```
ERROR: Could not find a version that satisfies the requirement echolab2 (from versions: none)
ERROR: No matching distribution found for echolab2
```

I resolved the issue by directly installing from the GitHub repository as follows:

```
pip install git+https://github.com/CI-CMG/pyEcholab.git
```

**Comment by simedroniraluca** [comment]
**This project is developed using Python 3.10.4**
